# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029f35fcc746bc15e853fb1fecd6b81710269a4c687bd5856da1bce772d4498b16a4041f6219115a46228e47fed7e099aaef3d19a9fa8d2c2fdb1b22f905e530

test:
  secret_key_base: 1edb6209d7b4b2d06833090363d9df79e78fc3a18c2a103eac65ddcb710e11f224370e7fa6596d35d222948c4c840430ae2a136eedb28bfd1bd295b31b1261a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
